[main][feat] TLCHook calculate weight when mint()
HMXOrg/v2-evm pull request #271
Opened 2023-07-06 05:31 UTC by Asaki-Katsu

Add weight logic when minting TLC token depends on marketIndex.

2023-07-06 05:34 UTC, john-xina-p88 commented on src/staking/TLCHook.sol
> +  error WeightIsZero();
```suggestion
  error TLCHook_Forbidden();
  error TLCHook_WeightIsZero();
```

2023-07-06 05:34 UTC, john-xina-p88 commented on src/staking/TLCHook.sol
> +  mapping(uint256 => uint256) public marketWeights;
```suggestion
  mapping(uint256 marketIndex => uint256 weight) public marketWeights;
```
and please add comment to describe what does this state do

2023-07-06 05:36 UTC, john-xina-p88 commented on src/staking/TLCHook.sol
> +    marketWeights[_marketIndex] = _weight;
```suggestion
    emit LogSetMarketWeight(_marketIndex, oldWeight, newWeight);
    marketWeights[_marketIndex] = _weight;
```
add event to log every `setMarketWeight` call

2023-07-06 07:29 UTC, john-xina-p88 commented on src/staking/TLCHook.sol
> +  event SetMarketWeight(uint256 marketIndex, uint256 weight);
```suggestion
  event LogSetMarketWeight(uint256 marketIndex, uint256 weight);
```

2023-07-06 07:49 UTC, john-xina-p88 approved these changes

2023-07-06 08:11 UTC, shutsuwei requested changes

2023-07-06 08:11 UTC, shutsuwei commented on src/staking/TLCHook.sol
> +  uint256 internal constant BPS = 10_000;
uint32 should be more than enough to fit BPS
and format should be `100_00`

2023-07-06 08:11 UTC, shutsuwei commented on src/staking/TLCHook.sol
> +    uint256 _mintAmount = _sizeDelta.mulDiv(weight, 1e12) / BPS;
can optimized math here. Instead of `mulDiv(weight, 1e12)` you can do `mulDiv(weight, 1e12 * BPS)`

2023-07-06 08:11 UTC, shutsuwei commented on src/staking/TLCHook.sol
> +    uint256 oldWeight = marketWeights[_marketIndex];
No need to cached oldWeight just for log, you can log before update the state

2023-07-08 15:26 UTC, shutsuwei requested changes

2023-07-08 15:26 UTC, shutsuwei commented on src/staking/TLCHook.sol
> +import { FullMath } from "../libraries/FullMath.sol";
`@hmx/libraries/FullMath.sol`

2023-07-11 03:59 UTC, shutsuwei approved these changes

2023-07-11 03:59 UTC, merged