[main] [feat] position size limit
HMXOrg/v2-evm pull request #283
Opened 2023-07-17 04:55 UTC by john-xina-p88

2023-07-19 05:58 UTC, shutsuwei requested changes

2023-07-19 05:58 UTC, shutsuwei commented on configs/arbitrum.goerli.json
> +    "maxPositionHelper": ""
probably better naming than `maxPositionHelper` something like `limitHandlerExtension` or `limitHandlerHelper` so it is not too specific

2023-07-19 05:58 UTC, shutsuwei commented on src/helpers/MaxPositionHelper.sol
> +    uint8 assetClass = configStorage.getMarketConfigByIndex(marketIndex).assetClass;
local vars prefix with `_`

2023-07-20 03:52 UTC, shutsuwei requested changes

2023-07-20 03:52 UTC, shutsuwei commented on script/ts/configs/LimitTradeHandler/set-limit-trade-helper.ts
> +  console.log("> LimitTradeHandler: Set Max Position Helper...");
Set limit Trade Helper

2023-07-20 03:52 UTC, shutsuwei commented on script/ts/configs/LimitTradeHandler/set-limit-trade-helper.ts
> +  console.log("> LimitTradeHandler: Set Max Position Helper success!");
Set Limit Trade Helper success

2023-07-20 03:52 UTC, shutsuwei commented on script/ts/configs/LimitTradeHelper/set-position-size-limit.ts
>    const positionSizeLimit = ethers.utils.parseUnits("500000", 30);
make this params an array instead of a single set.

2023-07-20 03:52 UTC, shutsuwei commented on src/helpers/LimitTradeHelper.sol
> +  constructor(address _configStorage, address _perpStorage) Ownable() {
don't think need `Ownable()` here

2023-07-20 03:52 UTC, shutsuwei commented on src/helpers/LimitTradeHelper.sol
> +  error MaxTradeSize();
LimitTradeHelper_MaxTradeSize()

2023-07-20 03:52 UTC, shutsuwei commented on src/helpers/LimitTradeHelper.sol
> +    // Not logging event to save gas
I think it is ok to log here. So interns can build Dune over it.

2023-07-20 03:53 UTC, shutsuwei commented
Can you also write a fork test to make sure users will be able to close existed position which larger than the limit?

2023-07-20 05:38 UTC, john-xina-p88 commented
Failed job is from fork test

2023-07-20 10:00 UTC, shutsuwei approved these changes

2023-07-21 08:42 UTC, merged