[main][feat] deploy script switch collateral router & dextors
HMXOrg/v2-evm pull request #302
Opened 2023-08-16 11:01 UTC by Asaki-Katsu

2023-08-16 11:18 UTC, john-xina-p88 commented on script/ts/commands/Dexter/curve-setPoolConfigs.ts
> +  console.log("[CurveDexter] Finished");
Make this a loop and let user config whatever we like

2023-08-16 11:20 UTC, john-xina-p88 commented on configs/arbitrum.goerli.json
> +    "curveWstEthPool": ""
these should be in vendors
```
"vendors": {
    "gmx": {
      "glpManager": "0x3963FfC9dff443c2A94f21b129D429891E32ec18",
      "rewardRouterV2": "0xB95DB5B167D75e6d04227CfFFA61069348d271F5",
      "rewardTracker": "0x4e971a87900b931fF39d1Aad67697F49835400b6"
      "gmxVault": ""
    },
    "uniswap": {
      "permit2": "0x000000000022d473030f116ddee9f6b43ac78ba3",
      "universalRouter": "0x3fC91A3afd70395Cd496C647d5a6CC9D4B2b7FAD"
    },
    "curve": {
       "wstEthPool": ""
    }
  },
```

2023-08-16 11:21 UTC, john-xina-p88 commented on script/ts/commands/Dexter/uniswap-setPath.ts
> +import { Command } from "commander";
kebab case name pls

2023-08-16 11:21 UTC, john-xina-p88 commented on script/ts/commands/Dexter/uniswap-setPath.ts
> +  console.log(`[UniswapDexter] Tx - Set Path of (WETH, ARB): ${tx2.hash}`);
loop

2023-08-16 11:22 UTC, john-xina-p88 commented on script/ts/commands/SwitchCollateralRouter/setDexter.ts
> +import { Command } from "commander";
kebab case name

2023-08-16 11:22 UTC, john-xina-p88 commented on script/ts/commands/SwitchCollateralRouter/setDexter.ts
> +  const dexter = SwitchCollateralRouter__factory.connect(config.extension.switchCollateralRouter, deployer);
loop

2023-08-16 12:11 UTC, shutsuwei requested changes

2023-08-16 12:11 UTC, shutsuwei commented on script/ts/commands/Dexter/uniswap-set-path.ts
> +  console.log("[UniswapDexter] Setting path config...");
[cmds/UniswapDexter]

2023-08-16 12:11 UTC, shutsuwei commented on script/ts/commands/SwitchCollateralRouter/set-dexter.ts
> +    console.log(`[SwitchCollateral] Tx - Set Dexter of (${params[i].tokenIn}, ${params[i].tokenOut}): ${tx.hash}`);
[cmds/SwitchCollateralRouter]

2023-08-16 12:11 UTC, shutsuwei commented on script/ts/deploys/Dexter/curve.ts
> +  console.log(`Deploying CurveDexter Contract`);
[deploys/Dexter]

2023-08-16 12:11 UTC, shutsuwei commented on script/ts/deploys/Dexter/glp.ts
> +  console.log(`Deploying GlpDexter Contract`);
[deploys/Dexter]

2023-08-16 12:11 UTC, shutsuwei commented on script/ts/deploys/Dexter/uniswapV3.ts
> +  console.log(`Deploying UniswapDexter Contract`);
[deploys/Dexter]

2023-08-16 12:11 UTC, shutsuwei commented on script/ts/deploys/SwitchCollateralRouter/index.ts
> +  console.log(`Deploying SwitchCollateralRouter Contract`);
[deploys/SwitchCollateralRouter]

2023-08-17 04:14 UTC, john-xina-p88 approved these changes

2023-08-17 11:34 UTC, closed without merging