[main] [feat] improve reserve calculation to support params adjustment
HMXOrg/v2-evm pull request #314
Opened 2023-08-25 04:22 UTC by john-xina-p88

2023-08-25 07:51 UTC, shutsuwei requested changes

2023-08-25 07:51 UTC, shutsuwei commented on src/services/TradeService.sol
> +      // update global storage by removing the reserveValueE30 of the position first
update -> Update

2023-08-25 07:53 UTC, shutsuwei commented
Can you add a fork test updating params?

2023-08-29 03:49 UTC, kim-hera approved these changes

2023-08-29 07:54 UTC, shutsuwei approved these changes

2023-08-30 07:02 UTC, merged