[main] [feat] subsidize execution fee
HMXOrg/v2-evm pull request #417
Opened 2024-04-10 06:45 UTC by john-xina-p88

2024-04-10 08:29 UTC, jinlong9922 approved these changes

2024-04-10 08:39 UTC, shutsuwei requested changes

2024-04-10 08:39 UTC, shutsuwei commented on src/services/GasService.sol
> +  bool public isExecutionFeeSubsidization;
Don't think we need this variable as we can adjust `waivedExecutionFeeTradeSize` to 0 to disable

2024-04-10 08:39 UTC, shutsuwei commented on src/services/GasService.sol
> +  uint256 public waivedExecutionFeeTradeSize; // The minimum trade size (E30) that we will waive exeuction fee
do we need 2 slots for these variables?

2024-04-10 08:44 UTC, shutsuwei requested changes

2024-04-10 08:44 UTC, shutsuwei commented on src/services/GasService.sol
> +  uint256 public waivedExecutionFeeTradeSize; // The minimum trade size (E30) that we will waive exeuction fee
`waviedExecutionFeeTradeSize` -> `waviedExecutionFeeMinFeeTradeSize`

2024-04-11 13:03 UTC, shutsuwei approved these changes

2024-04-11 13:03 UTC, merged